### PR TITLE
Bugfix: make committed rows visible (fixes #15)

### LINKED ISSUE #15: Bug: Committed rows can become invisible to new transactions
The paper has a typo, which I have confirmed with one of the authors. Since the code closely follows the paper and the bug has crept in here. 

Let me explain with a diagram, following the same conventions as the paper:

Untitled-2023-04-10-1232

1. At time 60, we observe our initial state, where the value of Larry is 170. This is a committed row.
2. At time 75, a transaction is started and is in Active state. It wants to update the value to 150, so it appended row 2
3. At time 80, another new transaction, Tx80 is started, and it wants to read the value of Larry. Both Tx75 and Tx80 are in Active state. 

What is the value Tx80 going to read?

Tx80 can't see row 2 because of Table 1 rules. If Tx75 is in Active state, only Tx75 can see row 2. This makes sense because row 2 is fresh, and Tx75 might drop the changes later. We don't want any other transactions to see this row.

But can Tx80 see row 1? The rules from the paper contradict that since Tx75 is in Active state:

Screenshot 2023-04-09 at 11 51 24 PM

This is a typo, and Tx80 should be able to see row 1 since it is a committed row. 

## Code

This is the line which causes this bug - https://github.com/penberg/mvcc-rs/blob/44df6c/database/src/database.rs#L438

We can reproduce this error: 
1. Lets first insert a new row and commit it 
2. Start a new transaction `te`, updating this row. Let `te` be in active state 
3. Start one more transaction `tx`. Let this be in the active state too. According to the code, `tx` won't see the committed value.

## Fix

- `tx` should be able to see this row
- `te` should not see this, instead the version it is updating (e.g. row2 from the previous diagram)
-  usual rules about the time ranges apply

### PR DESCRIPTION
**Pull request by avinassh**

### CODE REVIEW

File: database/src/database.rs [hunk 1]
```diff
@@ -723,4 +723,61 @@ mod tests {
...
+        db.insert(tx1, tx1_row.clone()).await.unwrap();
+        db.commit_tx(tx1).await.unwrap();
+
+        // but I like more money, so let me try adding $10 more
+        let tx2 = db.begin_tx().await;
+        let tx2_row = Row {
+            id: 1,
+            data: "20".to_string(),
+        };
+        assert!(db.update(tx2, tx2_row.clone()).await.unwrap());
```
Comment (penberg) [inline database/src/database.rs:750]: Can you add an assertion here to check that `read(tx2, 1)` returns `tx2_row`?

Comment (avinassh) [reply database/src/database.rs:750]: @penberg I have added this assert

**Comment by penberg** [comment]
To explain the rationale of this change for future reads:

```patch
diff --git a/database/src/database.rs b/database/src/database.rs
index 6a1c7ac..05a6624 100644
--- a/database/src/database.rs
+++ b/database/src/database.rs
@@ -435,7 +435,7 @@ fn is_end_visible(txs: &HashMap<TxID, Transaction>, tx: &Transaction, rv: &RowVe
         Some(TxTimestampOrID::TxID(rv_end)) => {
             let te = txs.get(&rv_end).unwrap();
             match te.state {
-                TransactionState::Active => tx.tx_id == te.tx_id && rv.end.is_none(),
+                TransactionState::Active => tx.tx_id != te.tx_id,
                 TransactionState::Preparing => todo!(),
                 TransactionState::Committed => todo!(),
                 TransactionState::Aborted => todo!(),
```

If an active transaction has deleted a version, it is not supposed to see that version anymore. However, other transactions _are_ supposed to see the old version because that's the latest committed version.
